### ISSUE TITLE
i am use webpack 

### ISSUE THREAD

**Issue by Keyty** [Nolanus/ng2-page-scroll#148]
i am use webpack and i have already import it to my AppModule and when i run it, it encourate a problem 
reflection_capabilities.js:63 Uncaught TypeError: ctorParameters.map is not a function
    at ReflectionCapabilities.parameters (http://localhost:3000/client-bundle.js:59916:47)
    at Reflector.parameters (http://localhost:3000/client-bundle.js:60127:48)
    at CompileMetadataResolver.getDependenciesMetadata (http://localhost:3000/client-bundle.js:41032:156)
    at CompileMetadataResolver.getTypeMetadata (http://localhost:3000/client-bundle.js:40997:26)
    at CompileMetadataResolver.getProviderMetadata (http://localhost:3000/client-bundle.js:41192:40)
    at http://localhost:3000/client-bundle.js:41140:45
    at Array.forEach (native)
    at CompileMetadataResolver.getProvidersMetadata (http://localhost:3000/client-bundle.js:41124:19)
    at http://localhost:3000/client-bundle.js:40816:71
    at Array.forEach (native)

What should I do to deal with that.thanks very much!

**Comment by Nolanus** [comment]
Hi,

this is not an issue related to this library. Please check https://stackoverflow.com/questions/41285889/ctorparameters-map-is-not-a-function-in-angular2-mdl or one of the other helpful links appearing when [googling the error message](https://www.google.de/search?q=Uncaught+TypeError%3A+ctorParameters.map+is+not+a+function).
