### ISSUE TITLE
ng serve in demo folder gives this crypto error.

### ISSUE THREAD

**Issue by rafialikhan** [Nolanus/ng2-page-scroll#189]
Cloned the repo. Did npm run demo. 

OS: Mac OS X El Capitan
Node Version: v6.10.0
npm -v: 4.4.4

Also any possibility of a setting up a live demo, so we can take a quick look if this is the right component someone wants to use. It took me almost 1/2 hour to get npm install to complete and then this...

[Seems to be a webpack issue](https://github.com/webpack/webpack/issues/4072) - then again not, its an angular material issue. read my next comment.

```** NG Live Development Server is listening on 0.0.0.0:4200, open your browser on http://localhost:4200 **
 86% hashingcrypto.js:74                                                                 
  this._handle.update(data, encoding);
               ^

TypeError: Data must be a string or a buffer
    at TypeError (native)
    at Hash.update (crypto.js:74:16)
    at HarmonyExportImportedSpecifierDependency.updateHash (/Users/****/Projects/test/ng2-scroll/ng2-page-scroll/demo/node_modules/webpack/lib/dependencies/HarmonyExportImportedSpecifierDependency.js:144:8)
    at /Users/*****/Projects/test/ng2-scroll/ng2-page-scroll/demo/node_modules/webpack/lib/DependenciesBlock.js:33:5
    at Array.forEach (native)
    at NormalModule.DependenciesBlock.updateHash (/Users/*****/Projects/test/ng2-scroll/ng2-page-scroll/demo/node_modules/webpack/lib/DependenciesBlock.js:32:20)
    at NormalModule.Module.updateHash (/Users/****/Projects/test/ng2-scroll/ng2-page-scroll/demo/node_modules/webpack/lib/Module.js:162:41)
    at NormalModule.updateHash (/Users/****/Projects/test/ng2-scroll/ng2-page-scroll/demo/node_modules/webpack/lib/NormalModule.js:327:30)
    at modules.forEach.m (/Users/****/Projects/test/ng2-scroll/ng2-page-scroll/demo/node_modules/webpack/lib/Chunk.js:253:31)
    at Array.forEach (native)
    at Chunk.updateHash (/Users/****/Projects/test/ng2-scroll/ng2-page-scroll/demo/node_modules/webpack/lib/Chunk.js:253:16)
    at Compilation.createHash (/Users/****/Projects/test/ng2-scroll/ng2-page-scroll/demo/node_modules/webpack/lib/Compilation.js:1121:10)
    at sealPart2 (/Users/****/Projects/test/ng2-scroll/ng2-page-scroll/demo/node_modules/webpack/lib/Compilation.js:605:9)
    at next (/Users/****/Projects/test/ng2-scroll/ng2-page-scroll/demo/node_modules/tapable/lib/Tapable.js:138:11)
    at Compilation.<anonymous> (/Users/****/Projects/test/ng2-scroll/ng2-page-scroll/demo/node_modules/webpack/lib/ProgressPlugin.js:110:5)
    at Compilation.applyPluginsAsyncSeries (/Users/****/Projects/test/ng2-scroll/ng2-page-scroll/demo/node_modules/tapable/lib/Tapable.js:142:13)```

**Comment by rafialikhan** [comment]
Changing the version of angular material to     "@angular/material": "2.0.0-beta.5" instead of     "@angular/material": "^2.0.0-beta.5" worked. Apparently angular material now needs @angular/cdk 

https://github.com/angular/material2/blob/master/guides/getting-started.md#step-1-install-angular-material-and-angular-cdk

**Comment by Nolanus** [comment]
Sorry for the late follow up.
`ng2-page-scroll`does not have a dependency on @angular/material, but the demo application, which is included in the git repo, does. However, the demo app is not shipped via npm.
