### ISSUE TITLE
Cannot resolve symbol 'PageScroll' when using with Angular-CLI 

### ISSUE THREAD

**Issue by thehashrocket** [Nolanus/ng2-page-scroll#25]
I followed the instructions [here](https://github.com/angular/angular-cli/wiki/3rd-party-libs) to add ng2-page-scroll into my existing angular-cli project. 

The directory looks like this:
![myorder_component_ts_-_angular-apps_-____projects_angular-apps_](https://cloud.githubusercontent.com/assets/342353/17493329/0c08ccc6-5d6d-11e6-973e-7bb95df9e53d.png)

So I know that the `ng build` command is working and copying over the files. Is it missing something? 

My angular-cli-build.js file:

```
module.exports = function(defaults) {
  return new Angular2App(defaults, {
    vendorNpmFiles: [
      'systemjs/dist/system-polyfills.js',
      'systemjs/dist/system.src.js',
      'zone.js/dist/**/*.+(js|js.map)',
      'es6-shim/es6-shim.js',
      'reflect-metadata/**/*.+(ts|js|js.map)',
      'rxjs/**/*.+(js|js.map)',
      '@angular/**/*.+(js|js.map)',
      'ng2-file-upload/**/*.js',
      'ng2-page-scroll/**/*.ts'
    ]
  });
};
```

And system-config.ts file:

```
const map: any = {
  'ng2-file-upload': 'vendor/ng2-file-upload',
  'ng2-page-scroll': 'vendor/ng2-page-scroll'
};

/** User packages configuration. */
const packages: any = {
  'ng2-file-upload': { defaultExtension: 'js'},
  'ng2-page-scroll': { defaultExtension: 'ts', main: 'ng2-page-scroll.ts'}
};
```

From all accounts, it should work, but it just keeps erroring for some reason.

**Comment by Nolanus** [comment]
The ng2-page-scroll directory looks quite empty. In a fresh "npm install"ation of ng2-page-scroll there are precompiled *.js files you may use

**Comment by thehashrocket** [comment]
@Nolanus which is the precompiled .js file I want to use? I went ahead and manually copied the entire folder into the vendor folder. Pagescroll cannot be found still. 

![myorder_component_ts_-_angular-apps_-____projects_angular-apps_](https://cloud.githubusercontent.com/assets/342353/17516833/f78f1c00-5dfd-11e6-9ab4-e7bc9d3398c5.png)

**Comment by Nolanus** [comment]
Where did you manually copy the folder from?
Try running `npm install`, `npm run compile` and `node make.js` in the folder, that should get the dependencies and build the project.

**Comment by thehashrocket** [comment]
i copied it from `node_modules` directly to `vendor`.

If I just do like you asked, and did the npm install, etc. this is what happens:


```
➜  ng2-page-scroll git:(3211_3form_click_to_order) ✗ npm run compile

> ng2-page-scroll@1.2.1 compile /Users/jasonshultz/Projects/angular-apps/node_modules/ng2-page-scroll
> tsc && npm run lint

../@angular/common/src/directives/ng_class.d.ts(81,35): error TS2304: Cannot find name 'Set'.
../@angular/common/src/facade/async.d.ts(34,33): error TS2304: Cannot find name 'Promise'.
../@angular/common/src/facade/async.d.ts(35,45): error TS2304: Cannot find name 'Promise'.
../@angular/common/src/facade/lang.d.ts(11,17): error TS2304: Cannot find name 'Map'.
../@angular/common/src/facade/lang.d.ts(12,17): error TS2304: Cannot find name 'Set'.
../@angular/common/src/facade/lang.d.ts(68,59): error TS2304: Cannot find name 'Map'.
../@angular/common/src/facade/promise.d.ts(9,14): error TS2304: Cannot find name 'Promise'.
../@angular/common/src/facade/promise.d.ts(15,32): error TS2304: Cannot find name 'Promise'.
../@angular/common/src/facade/promise.d.ts(16,38): error TS2304: Cannot find name 'Promise'.
../@angular/common/src/facade/promise.d.ts(17,35): error TS2304: Cannot find name 'Promise'.
../@angular/common/src/facade/promise.d.ts(17,93): error TS2304: Cannot find name 'Promise'.
../@angular/common/src/facade/promise.d.ts(18,34): error TS2304: Cannot find name 'Promise'.
../@angular/common/src/facade/promise.d.ts(18,50): error TS2304: Cannot find name 'Promise'.
../@angular/common/src/facade/promise.d.ts(19,32): error TS2304: Cannot find name 'Promise'.
../@angular/common/src/facade/promise.d.ts(19,149): error TS2304: Cannot find name 'Promise'.
../@angular/common/src/facade/promise.d.ts(20,43): error TS2304: Cannot find name 'Promise'.
../@angular/common/src/pipes/async_pipe.d.ts(41,38): error TS2304: Cannot find name 'Promise'.
../@angular/core/src/application_ref.d.ts(79,88): error TS2304: Cannot find name 'Promise'.
../@angular/core/src/application_ref.d.ts(137,42): error TS2304: Cannot find name 'Promise'.
../@angular/core/src/application_ref.d.ts(196,33): error TS2304: Cannot find name 'Promise'.
../@angular/core/src/change_detection/differs/default_keyvalue_differ.d.ts(24,15): error TS2304: Cannot find name 'Map'.
../@angular/core/src/change_detection/differs/default_keyvalue_differ.d.ts(26,16): error TS2304: Cannot find name 'Map'.
../@angular/core/src/di/reflective_provider.d.ts(115,123): error TS2304: Cannot find name 'Map'.
../@angular/core/src/di/reflective_provider.d.ts(115,165): error TS2304: Cannot find name 'Map'.
../@angular/core/src/facade/async.d.ts(34,33): error TS2304: Cannot find name 'Promise'.
../@angular/core/src/facade/async.d.ts(35,45): error TS2304: Cannot find name 'Promise'.
../@angular/core/src/facade/collection.d.ts(1,25): error TS2304: Cannot find name 'MapConstructor'.
../@angular/core/src/facade/collection.d.ts(2,25): error TS2304: Cannot find name 'SetConstructor'.
../@angular/core/src/facade/collection.d.ts(4,27): error TS2304: Cannot find name 'Map'.
../@angular/core/src/facade/collection.d.ts(4,39): error TS2304: Cannot find name 'Map'.
../@angular/core/src/facade/collection.d.ts(7,9): error TS2304: Cannot find name 'Map'.
../@angular/core/src/facade/collection.d.ts(8,30): error TS2304: Cannot find name 'Map'.
../@angular/core/src/facade/collection.d.ts(11,43): error TS2304: Cannot find name 'Map'.
../@angular/core/src/facade/collection.d.ts(12,27): error TS2304: Cannot find name 'Map'.
../@angular/core/src/facade/collection.d.ts(14,23): error TS2304: Cannot find name 'Map'.
../@angular/core/src/facade/collection.d.ts(15,25): error TS2304: Cannot find name 'Map'.
../@angular/core/src/facade/collection.d.ts(100,41): error TS2304: Cannot find name 'Set'.
../@angular/core/src/facade/collection.d.ts(101,22): error TS2304: Cannot find name 'Set'.
../@angular/core/src/facade/collection.d.ts(102,25): error TS2304: Cannot find name 'Set'.
../@angular/core/src/facade/lang.d.ts(11,17): error TS2304: Cannot find name 'Map'.
../@angular/core/src/facade/lang.d.ts(12,17): error TS2304: Cannot find name 'Set'.
../@angular/core/src/facade/lang.d.ts(68,59): error TS2304: Cannot find name 'Map'.
../@angular/core/src/facade/promise.d.ts(9,14): error TS2304: Cannot find name 'Promise'.
../@angular/core/src/facade/promise.d.ts(15,32): error TS2304: Cannot find name 'Promise'.
../@angular/core/src/facade/promise.d.ts(16,38): error TS2304: Cannot find name 'Promise'.
../@angular/core/src/facade/promise.d.ts(17,35): error TS2304: Cannot find name 'Promise'.
../@angular/core/src/facade/promise.d.ts(17,93): error TS2304: Cannot find name 'Promise'.
../@angular/core/src/facade/promise.d.ts(18,34): error TS2304: Cannot find name 'Promise'.
../@angular/core/src/facade/promise.d.ts(18,50): error TS2304: Cannot find name 'Promise'.
../@angular/core/src/facade/promise.d.ts(19,32): error TS2304: Cannot find name 'Promise'.
../@angular/core/src/facade/promise.d.ts(19,149): error TS2304: Cannot find name 'Promise'.
../@angular/core/src/facade/promise.d.ts(20,43): error TS2304: Cannot find name 'Promise'.
../@angular/core/src/linker/compiler.d.ts(13,59): error TS2304: Cannot find name 'Promise'.
../@angular/core/src/linker/component_resolver.d.ts(9,58): error TS2304: Cannot find name 'Promise'.
../@angular/core/src/linker/component_resolver.d.ts(13,49): error TS2304: Cannot find name 'Promise'.
../@angular/core/src/linker/dynamic_component_loader.d.ts(61,148): error TS2304: Cannot find name 'Promise'.
../@angular/core/src/linker/dynamic_component_loader.d.ts(102,144): error TS2304: Cannot find name 'Promise'.
../@angular/core/src/linker/dynamic_component_loader.d.ts(107,139): error TS2304: Cannot find name 'Promise'.
../@angular/core/src/linker/dynamic_component_loader.d.ts(108,135): error TS2304: Cannot find name 'Promise'.
../@angular/core/src/linker/systemjs_component_resolver.d.ts(18,53): error TS2304: Cannot find name 'Promise'.
../@angular/core/src/linker/systemjs_component_resolver.d.ts(26,53): error TS2304: Cannot find name 'Promise'.
../@angular/platform-browser/src/dom/dom_adapter.d.ts(96,42): error TS2304: Cannot find name 'Map'.
../@angular/platform-browser/src/dom/dom_renderer.d.ts(17,37): error TS2304: Cannot find name 'Map'.
../@angular/platform-browser/src/facade/async.d.ts(34,33): error TS2304: Cannot find name 'Promise'.
../@angular/platform-browser/src/facade/async.d.ts(35,45): error TS2304: Cannot find name 'Promise'.
../@angular/platform-browser/src/facade/collection.d.ts(1,25): error TS2304: Cannot find name 'MapConstructor'.
../@angular/platform-browser/src/facade/collection.d.ts(2,25): error TS2304: Cannot find name 'SetConstructor'.
../@angular/platform-browser/src/facade/collection.d.ts(4,27): error TS2304: Cannot find name 'Map'.
../@angular/platform-browser/src/facade/collection.d.ts(4,39): error TS2304: Cannot find name 'Map'.
../@angular/platform-browser/src/facade/collection.d.ts(7,9): error TS2304: Cannot find name 'Map'.
../@angular/platform-browser/src/facade/collection.d.ts(8,30): error TS2304: Cannot find name 'Map'.
../@angular/platform-browser/src/facade/collection.d.ts(11,43): error TS2304: Cannot find name 'Map'.
../@angular/platform-browser/src/facade/collection.d.ts(12,27): error TS2304: Cannot find name 'Map'.
../@angular/platform-browser/src/facade/collection.d.ts(14,23): error TS2304: Cannot find name 'Map'.
../@angular/platform-browser/src/facade/collection.d.ts(15,25): error TS2304: Cannot find name 'Map'.
../@angular/platform-browser/src/facade/collection.d.ts(100,41): error TS2304: Cannot find name 'Set'.
../@angular/platform-browser/src/facade/collection.d.ts(101,22): error TS2304: Cannot find name 'Set'.
../@angular/platform-browser/src/facade/collection.d.ts(102,25): error TS2304: Cannot find name 'Set'.
../@angular/platform-browser/src/facade/lang.d.ts(11,17): error TS2304: Cannot find name 'Map'.
../@angular/platform-browser/src/facade/lang.d.ts(12,17): error TS2304: Cannot find name 'Set'.
../@angular/platform-browser/src/facade/lang.d.ts(68,59): error TS2304: Cannot find name 'Map'.
../@angular/platform-browser/src/facade/promise.d.ts(9,14): error TS2304: Cannot find name 'Promise'.
../@angular/platform-browser/src/facade/promise.d.ts(15,32): error TS2304: Cannot find name 'Promise'.
../@angular/platform-browser/src/facade/promise.d.ts(16,38): error TS2304: Cannot find name 'Promise'.
../@angular/platform-browser/src/facade/promise.d.ts(17,35): error TS2304: Cannot find name 'Promise'.
../@angular/platform-browser/src/facade/promise.d.ts(17,93): error TS2304: Cannot find name 'Promise'.
../@angular/platform-browser/src/facade/promise.d.ts(18,34): error TS2304: Cannot find name 'Promise'.
../@angular/platform-browser/src/facade/promise.d.ts(18,50): error TS2304: Cannot find name 'Promise'.
../@angular/platform-browser/src/facade/promise.d.ts(19,32): error TS2304: Cannot find name 'Promise'.
../@angular/platform-browser/src/facade/promise.d.ts(19,149): error TS2304: Cannot find name 'Promise'.
../@angular/platform-browser/src/facade/promise.d.ts(20,43): error TS2304: Cannot find name 'Promise'.
../@angular/platform-browser/src/web_workers/shared/client_message_broker.d.ts(32,65): error TS2304: Cannot find name 'Promise'.
../@angular/platform-browser/src/web_workers/shared/client_message_broker.d.ts(40,56): error TS2304: Cannot find name 'Promise'.
../@angular/platform-browser/src/web_workers/shared/service_message_broker.d.ts(35,84): error TS2304: Cannot find name 'Promise'.
../@angular/platform-browser/src/web_workers/worker/location_providers.d.ts(21,86): error TS2304: Cannot find name 'Promise'.
../@angular/router/src/router.d.ts(188,43): error TS2304: Cannot find name 'Promise'.
../@angular/router/src/router.d.ts(204,59): error TS2304: Cannot find name 'Promise'.
../rxjs/Observable.d.ts(10,66): error TS2304: Cannot find name 'Promise'.
../rxjs/Observable.d.ts(66,60): error TS2304: Cannot find name 'Promise'.
../rxjs/Observable.d.ts(66,70): error TS2304: Cannot find name 'Promise'.

npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "compile"
npm ERR! node v4.4.0
npm ERR! npm  v2.14.20
npm ERR! code ELIFECYCLE
npm ERR! ng2-page-scroll@1.2.1 compile: `tsc && npm run lint`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the ng2-page-scroll@1.2.1 compile script 'tsc && npm run lint'.
npm ERR! This is most likely a problem with the ng2-page-scroll package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     tsc && npm run lint
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs ng2-page-scroll
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls ng2-page-scroll
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/jasonshultz/Projects/angular-apps/node_modules/ng2-page-scroll/npm-debug.log
```


```
➜  ng2-page-scroll git:(3211_3form_click_to_order) ✗ node make.js
module.js:327
    throw err;
    ^

Error: Cannot find module 'systemjs-builder'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/jasonshultz/Projects/angular-apps/node_modules/ng2-page-scroll/make.js:5:15)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
```

So I'm not sure this is the right way to go?

**Comment by Nolanus** [comment]
Oh, there's no `package.json` in your _ng2-page-scroll_ folder either...
During the installation or during copying stuff to your _app/vendor_ folder files got lost probably. Try running `npm install ng2-page-scroll` in an empty directory to get the correct contents of the _node_modules/ng2-page-scroll_ folder.

Anyhow, I would rethink my project setup, as manually copying files around doesn't seem to be the best approach.

**Comment by thehashrocket** [comment]
you're right. the proper way is like i was showing you here: https://github.com/angular/angular-cli/wiki/3rd-party-libs

then, when you run `ng build` it copies the folder over to the vendor folder when it creates the dev or production build.

**Comment by Nolanus** [comment]
Haven't work with angular-cli yet, so I'm not familiar with their process. Anyhow it should be similar to the way you include _ng2-file-upload_. What's the reason for taking the *.ts files from the _ng2-page-scroll_ instead of the *.js like you do for the file-upload?

**Comment by thehashrocket** [comment]
ok, that's interesting. if i npm install `ng2-file-upload` in my project it only does the ts files. if I do it in a fresh project, it does all the js files. . . . I wonder why that is?

It's downloading different versions of the project?

**Comment by thehashrocket** [comment]
@Nolanus Ok, I "think" I have it figured out.

So, I forked your project in order to make this (pull request)[https://github.com/Nolanus/ng2-page-scroll/pull/24] because I needed to upgrade the router and angular versions to the latest RC4.

I referenced that branch in my projects `package.json` and then did `npm install` based off that. Apparently that doesn't work right because it doesn't pull all the files compared to doing it directly from npm the normal way.

Once I took the files that were installed in the empty project and copied them over into the node_modules folder in my existing project, ran `ng build` and then it worked! sweet!

**Comment by Nolanus** [comment]
The semVer constraint "~2.0.0-rc.3" meets the 2.0.0-rc.4 version, so using rc.4 as peer dependency beside ng2-page-scroll is possible.

Correct, downloading the project from npm gives you the compiled *.js files, pulling the repo from github contains the sources only (then you need to compile it yourself).

**Comment by thehashrocket** [comment]
That's cool. thanks for your help, I'm glad it got figured out. On to the next part of my project! :)
